name: Pylint

on:
 push:
   branches:
   - master

env:
  PYTHON-VERSION: "3.8"
  FAIL-UNDER: 8

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python {{ env.PYTHON-VERSION }}
      uses: actions/setup-python@v3
      with:
        python-version: {{ env.PYTHON-VERSION }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint --rcfile=.pylintrc --fail-under=${{ env.FAIL-UNDER }} $(git ls-files '*.py')
