name: Pylint

on:
 push:
   branches:
   - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      python-version: "3.8"
      fail-under: 8
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python {{ strategy.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: {{ strategy.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint --rcfile=.pylintrc --fail-under=${{ strategy.fail-under }} $(git ls-files '*.py')
